inference:
  batch_size: 16
  device: auto
  max_length: 512
  num_workers: 4
  output_dir: ./results
  use_fp16: false
model:
  name: Plant DNAGPT BPE promoter strength leaf
  path: zhangtaolab/plant-dnagpt-BPE-promoter_strength_leaf
  source: huggingface
  task_info:
    describe: Predict promoter strength of a DNA sequence in tobacco leaves by using
      Plant DNAGPT model with BPE tokenizer.
    label_names: promoter strength in tobacco leaves
    num_labels: 1
    task_type: regression
  torch_dtype: float32
  trust_remote_code: true
task:
  label_names: promoter strength in tobacco leaves
  num_labels: 1
  task_type: regression
  threshold: 0.5
