inference:
  batch_size: 16
  device: auto
  max_length: 512
  num_workers: 4
  output_dir: ./results
  use_fp16: false
model:
  name: Plant DNAMamba 6mer open chromatin
  path: zhangtaolab/plant-dnamamba-6mer-open_chromatin
  source: huggingface
  task_info:
    describe: Predict whether a DNA sequence is in open chromatin regions in plants
      by using Plant DNAMamba model with 6mer tokenizer.
    label_names: &id001
    - Not open
    - Full open
    - Partial open
    num_labels: 3
    task_type: multiclass
    threshold: 0.5
  torch_dtype: float32
  trust_remote_code: true
task:
  label_names: *id001
  num_labels: 3
  task_type: multiclass
  threshold: 0.5
